name: Publish to pub.dev

on:
  push:
    tags: 
    - v[0-9]+.[0-9]+.[0-9]+

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: famedly/frontend-ci-templates/.github/workflows/publish-pub.yml@main
